name: webdav
version: 1.0.5-dev

author: timestee

description: easy webdav for dart,support basic auth,directories\files listing,upload\downliad.
homepage: https://github.com/timestee/dart-webdav

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  retry: ^2.0.0
  xml: ^3.5.0

dev_dependencies:
  pedantic: ^1.2.0
  test: '>=1.0.0 <2.0.0'
